use_frameworks!

platform :ios, '11.0'

target 'AFeng_NetWorkTool_Example' do
  pod 'AFeng_NetWorkTool', :path => '../'

  target 'AFeng_NetWorkTool_Tests' do
    inherit! :search_paths

    
  end
end
